/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.gui;

/**
 *
 * @author USER
 */
public class EligibilityFrame extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(EligibilityFrame.class.getName());

        /**
         * Creates new form EligibilityFrame
         */
        public EligibilityFrame() {
                initComponents();
                setLocationRelativeTo(null);
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                setupTable();
                wireEvents();
                loadTable();
                clearOverview();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                label2 = new java.awt.Label();
                jButton1 = new javax.swing.JButton();
                jTextField1 = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                jButton2 = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                pnlHeader = new javax.swing.JPanel();
                label1 = new java.awt.Label();
                jLabel9 = new javax.swing.JLabel();
                pnlOverview = new javax.swing.JPanel();
                lblStudentOverview = new java.awt.Label();
                btnCheck = new javax.swing.JButton();
                txtStudentId = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();
                btnRegister = new javax.swing.JButton();
                lblNameValue = new javax.swing.JLabel();
                lblEmailValue = new javax.swing.JLabel();
                lblMajorValue = new javax.swing.JLabel();
                lblYearValue = new javax.swing.JLabel();
                lblCgpaValue = new javax.swing.JLabel();
                lblFailedValue = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                btnClear = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                lblEligibilityBadge = new javax.swing.JLabel();
                pnlTable = new javax.swing.JPanel();
                jScrollPane5 = new javax.swing.JScrollPane();
                tblStudents = new javax.swing.JTable();
                lblfilter = new javax.swing.JLabel();
                cmbFilter = new javax.swing.JComboBox<>();
                btnRefresh = new javax.swing.JButton();

                jPanel2.setBackground(new java.awt.Color(237, 234, 234));
                jPanel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                jPanel2.setPreferredSize(new java.awt.Dimension(292, 430));

                label2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
                label2.setForeground(new java.awt.Color(0, 0, 0));
                label2.setText("Student Overview");

                jButton1.setBackground(new java.awt.Color(18, 45, 110));
                jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Check Eligibility");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
                jLabel1.setText("Student ID:");

                jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel2.setText("Student Name ");

                jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel11.setText("Failed Courses");

                jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel12.setText("CGPA");

                jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel13.setText("Year Of Study");

                jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel14.setText("Programme ");

                jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel15.setText("Email Address");

                jButton2.setBackground(new java.awt.Color(18, 45, 110));
                jButton2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
                jButton2.setForeground(new java.awt.Color(255, 255, 255));
                jButton2.setText("Register For Next Level");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel2Layout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(label2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(77, 77, 77))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(jLabel11)
                                                                                                                .addComponent(jLabel12)
                                                                                                                .addComponent(jLabel13)
                                                                                                                .addComponent(jLabel14)
                                                                                                                .addComponent(jLabel15)
                                                                                                                .addGroup(jPanel2Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel1)
                                                                                                                                .addGap(4, 4, 4)
                                                                                                                                .addComponent(jTextField1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                105,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(jButton1)))
                                                                                                .addContainerGap(18,
                                                                                                                Short.MAX_VALUE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                138,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(54, 54, 54)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(label2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                20,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel1))
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel2)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel15)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel14)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel13)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel12)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(11, Short.MAX_VALUE)));

                jPanel3.setBackground(new java.awt.Color(237, 234, 234));
                jPanel3.setPreferredSize(new java.awt.Dimension(520, 430));

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane4.setViewportView(jTable2);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jScrollPane4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                531, Short.MAX_VALUE)
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane4)
                                                                .addContainerGap()));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                pnlHeader.setBackground(new java.awt.Color(18, 45, 110));
                pnlHeader.setForeground(new java.awt.Color(18, 45, 110));

                label1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
                label1.setForeground(new java.awt.Color(255, 255, 255));
                label1.setText("Eligibility Check And Enrolment");

                jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
                jLabel9.setForeground(new java.awt.Color(255, 255, 255));
                jLabel9.setText("Review Student Academic Standing And Approve Progression");

                javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
                pnlHeader.setLayout(pnlHeaderLayout);
                pnlHeaderLayout.setHorizontalGroup(
                                pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlHeaderLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(pnlHeaderLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(label1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel9))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                pnlHeaderLayout.setVerticalGroup(
                                pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlHeaderLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(label1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel9)
                                                                .addContainerGap(16, Short.MAX_VALUE)));

                pnlOverview.setBackground(new java.awt.Color(237, 234, 234));
                pnlOverview.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                pnlOverview.setPreferredSize(new java.awt.Dimension(292, 430));

                lblStudentOverview.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
                lblStudentOverview.setForeground(new java.awt.Color(0, 0, 0));
                lblStudentOverview.setText("Student Overview");

                btnCheck.setBackground(new java.awt.Color(18, 45, 110));
                btnCheck.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
                btnCheck.setForeground(new java.awt.Color(255, 255, 255));
                btnCheck.setText("Check Eligibility");
                btnCheck.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCheckActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
                jLabel3.setText("Student ID:");

                jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel4.setText("Student Name ");

                jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel16.setText("Failed Courses");

                jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel17.setText("CGPA");

                jLabel18.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel18.setText("Year Of Study");

                jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel19.setText("Programme ");

                jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
                jLabel20.setText("Email Address");

                btnRegister.setBackground(new java.awt.Color(18, 45, 110));
                btnRegister.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
                btnRegister.setForeground(new java.awt.Color(255, 255, 255));
                btnRegister.setText("Register For Next Level");
                btnRegister.setEnabled(false);
                btnRegister.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegisterActionPerformed(evt);
                        }
                });

                lblNameValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblNameValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblNameValue.setText("-");

                lblEmailValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblEmailValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblEmailValue.setText("-");

                lblMajorValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblMajorValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblMajorValue.setText("-");

                lblYearValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblYearValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblYearValue.setText("-");

                lblCgpaValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblCgpaValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblCgpaValue.setText("-");

                lblFailedValue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblFailedValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                lblFailedValue.setText("-");

                jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel5.setText("Eligibility Status:");

                btnClear.setBackground(new java.awt.Color(255, 152, 0));
                btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12));
                btnClear.setForeground(new java.awt.Color(255, 255, 255));
                btnClear.setText("Clear");
                btnClear.setBorderPainted(false);
                btnClear.setFocusPainted(false);
                btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });

                btnBack.setBackground(new java.awt.Color(204, 0, 0));
                btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14));
                btnBack.setForeground(new java.awt.Color(255, 255, 255));
                btnBack.setText("← RETURN");
                btnBack.setBorderPainted(false);
                btnBack.setFocusPainted(false);
                btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                lblEligibilityBadge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblEligibilityBadge.setText("-");

                javax.swing.GroupLayout pnlOverviewLayout = new javax.swing.GroupLayout(pnlOverview);
                pnlOverview.setLayout(pnlOverviewLayout);
                pnlOverviewLayout.setHorizontalGroup(
                                pnlOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlOverviewLayout.createSequentialGroup()
                                                                .addGap(79, 79, 79)
                                                                .addComponent(lblStudentOverview,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOverviewLayout
                                                                .createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(pnlOverviewLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(pnlOverviewLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(pnlOverviewLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(jLabel3)
                                                                                                                                .addGap(4, 4, 4)
                                                                                                                                .addComponent(txtStudentId,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                105,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(jLabel20)
                                                                                                                .addComponent(jLabel19)
                                                                                                                .addComponent(jLabel18))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(pnlOverviewLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(lblYearValue,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(lblMajorValue,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(lblEmailValue,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(lblNameValue,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                pnlOverviewLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(btnCheck)
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                pnlOverviewLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(pnlOverviewLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel17)
                                                                                                                                .addComponent(jLabel16))
                                                                                                                .addGap(95, 95, 95)
                                                                                                                .addGroup(pnlOverviewLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(pnlOverviewLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(jLabel5,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                107,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addComponent(lblEligibilityBadge,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                141,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                                                .addComponent(lblCgpaValue,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(lblFailedValue,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))))
                                                                .addGap(17, 17, 17))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOverviewLayout
                                                                .createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(btnClear)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnRegister)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnBack)
                                                                .addGap(30, 30, 30)));
                pnlOverviewLayout.setVerticalGroup(
                                pnlOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlOverviewLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblStudentOverview,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                20,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnCheck,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                31,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtStudentId,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(lblNameValue))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel20)
                                                                                .addComponent(lblEmailValue))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel19)
                                                                                .addComponent(lblMajorValue))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel18)
                                                                                .addComponent(lblYearValue,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                13,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel17)
                                                                                .addComponent(lblCgpaValue))
                                                                .addGap(35, 35, 35)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(lblFailedValue))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                34,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblEligibilityBadge))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(pnlOverviewLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnClear)
                                                                                .addComponent(btnRegister,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                34,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnBack))
                                                                .addGap(11, 11, 11)));

                pnlTable.setBackground(new java.awt.Color(237, 234, 234));
                pnlTable.setPreferredSize(new java.awt.Dimension(520, 430));

                tblStudents.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Student ID", "Student Name", "Major", "Year", "CGPA", "Failed",
                                                "Eligible", "Registered"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane5.setViewportView(tblStudents);

                lblfilter.setText("Filter:");

                cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "All Students", "Eligible Students", "Not Eligible Students",
                                                "Registered Students" }));

                btnRefresh.setBackground(new java.awt.Color(46, 125, 50));
                btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12));
                btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
                btnRefresh.setText("Refresh");
                btnRefresh.setBorderPainted(false);
                btnRefresh.setFocusPainted(false);
                btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRefreshActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
                pnlTable.setLayout(pnlTableLayout);
                pnlTableLayout.setHorizontalGroup(
                                pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlTableLayout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblfilter)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cmbFilter,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                115,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnRefresh)
                                                                .addGap(30, 30, 30))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                541, Short.MAX_VALUE)
                                                                .addContainerGap()));
                pnlTableLayout.setVerticalGroup(
                                pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(pnlTableLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblfilter)
                                                                                .addComponent(cmbFilter,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(btnRefresh))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                486,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(pnlOverview,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                450,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(pnlTable,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(20, 20, 20)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(pnlHeader,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(pnlOverview,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                527,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(pnlTable,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                527,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jButton2ActionPerformed

        private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnCheckActionPerformed

        private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegisterActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnRegisterActionPerformed

        private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnClearActionPerformed

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_btnRefreshActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new EligibilityFrame().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnCheck;
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnRefresh;
        private javax.swing.JButton btnRegister;
        private javax.swing.JComboBox<String> cmbFilter;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTable jTable2;
        private javax.swing.JTextField jTextField1;
        private java.awt.Label label1;
        private java.awt.Label label2;
        private javax.swing.JLabel lblCgpaValue;
        private javax.swing.JLabel lblEligibilityBadge;
        private javax.swing.JLabel lblEmailValue;
        private javax.swing.JLabel lblFailedValue;
        private javax.swing.JLabel lblMajorValue;
        private javax.swing.JLabel lblNameValue;
        private java.awt.Label lblStudentOverview;
        private javax.swing.JLabel lblYearValue;
        private javax.swing.JLabel lblfilter;
        private javax.swing.JPanel pnlHeader;
        private javax.swing.JPanel pnlOverview;
        private javax.swing.JPanel pnlTable;
        private javax.swing.JTable tblStudents;
        private javax.swing.JTextField txtStudentId;
        // End of variables declaration//GEN-END:variables
        private final crs.services.EligibilityService service = new crs.services.EligibilityService();
        private crs.services.EligibilityService.EligibilityResult current;
        private javax.swing.table.DefaultTableModel model;

        private void setupTable() {
                model = new javax.swing.table.DefaultTableModel(
                                new Object[] { "Student ID", "Student Name", "Major", "Year", "CGPA", "Failed",
                                                "Eligible",
                                                "Registered" },
                                0) {
                        @Override
                        public boolean isCellEditable(int r, int c) {
                                return false;
                        }
                };
                tblStudents.setModel(model);
                tblStudents.setRowHeight(24);
                tblStudents.getTableHeader().setReorderingAllowed(false);
        }

        private void wireEvents() {
                txtStudentId.addActionListener(e -> checkEligibility()); // press Enter to check

                btnCheck.addActionListener(e -> checkEligibility());
                btnRefresh.addActionListener(e -> loadTable());
                cmbFilter.addActionListener(e -> loadTable());

                btnClear.addActionListener(e -> {
                        txtStudentId.setText("");
                        clearOverview();
                        tblStudents.clearSelection();
                });

                btnRegister.addActionListener(e -> registerStudent());

                tblStudents.getSelectionModel().addListSelectionListener(e -> {
                        if (e.getValueIsAdjusting())
                                return;
                        int row = tblStudents.getSelectedRow();
                        if (row >= 0) {
                                String id = model.getValueAt(row, 0).toString();
                                txtStudentId.setText(id);
                                checkEligibility();
                        }
                });

                if (btnBack != null) {
                        btnBack.addActionListener(e -> dispose());
                }
        }

        private void loadTable() {
                model.setRowCount(0);

                String filter = (String) cmbFilter.getSelectedItem();
                java.util.Set<String> registered = service.registeredIds();

                for (crs.services.EligibilityService.EligibilityResult r : service.listAll()) {
                        boolean isReg = registered.contains(r.studentId);

                        if ("Eligible Students".equals(filter) && !r.eligible)
                                continue;
                        if ("Not Eligible Students".equals(filter) && r.eligible)
                                continue;
                        if ("Registered Students".equals(filter) && !isReg)
                                continue;

                        model.addRow(new Object[] {
                                        r.studentId,
                                        r.fullName,
                                        r.major,
                                        r.year,
                                        String.format("%.2f", r.cgpa),
                                        r.failed,
                                        r.eligible ? "Yes" : "No",
                                        isReg ? "Registered" : "Not Registered"
                        });
                }
        }

        private void checkEligibility() {
                String id = txtStudentId.getText().trim();
                if (id.isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Please Enter A Student ID.");
                        return;
                }

                current = service.checkStudent(id);
                if (current == null) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Student Not Found.");
                        clearOverview();
                        return;
                }

                lblNameValue.setText(current.fullName);
                lblEmailValue.setText(current.email);
                lblMajorValue.setText(current.major);
                lblYearValue.setText(current.year);
                lblCgpaValue.setText(String.format("%.2f", current.cgpa));
                lblFailedValue.setText(String.valueOf(current.failed));

                boolean isRegistered = service.registeredIds().contains(current.studentId);

                if (current.eligible) {
                        setBadge("Eligible", new java.awt.Color(224, 255, 235), new java.awt.Color(22, 110, 60));
                        btnRegister.setEnabled(!isRegistered);
                } else {
                        setBadge("Not Eligible", new java.awt.Color(255, 230, 230),
                                        new java.awt.Color(160, 40, 40));
                        btnRegister.setEnabled(false);
                }
        }

        private void registerStudent() {
                if (current == null) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Please Check A Student First.");
                        return;
                }
                if (!current.eligible) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Only Eligible Students Can Register.");
                        return;
                }

                java.util.Set<String> registered = service.registeredIds();
                if (registered.contains(current.studentId)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Student Already Registered.");
                        btnRegister.setEnabled(false);
                        return;
                }

                service.register(current.studentId);
                javax.swing.JOptionPane.showMessageDialog(this, "Student Registered Successfully.");
                loadTable();
                checkEligibility();
        }

        private void clearOverview() {
                lblNameValue.setText("-");
                lblEmailValue.setText("-");
                lblMajorValue.setText("-");
                lblYearValue.setText("-");
                lblCgpaValue.setText("-");
                lblFailedValue.setText("-");
                setBadge("Eligibility Status", new java.awt.Color(240, 240, 240), new java.awt.Color(90, 90, 90));
                btnRegister.setEnabled(false);
                current = null;
        }

        private void setBadge(String text, java.awt.Color bg, java.awt.Color fg) {
                lblEligibilityBadge.setText(text);
                lblEligibilityBadge.setOpaque(true);
                lblEligibilityBadge.setBackground(bg);
                lblEligibilityBadge.setForeground(fg);
                lblEligibilityBadge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblEligibilityBadge.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        }
}
