/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.gui;

import crs.services.EmailService;
import crs.services.UserService;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(ForgotPasswordFrame.class.getName());
    private String generatedOtp;
    private String verifiedEmail;
    private String verifiedUsername;

    /**
     * Creates new form ForgotPasswordFrame
     */
    public ForgotPasswordFrame() {
        initComponents();
        ResetOtp.setEnabled(false);
        VerifyReset.setEnabled(false);
        ResetNewPassword.setEnabled(false);
        ShowPasswordReset.setEnabled(false);
        ResetPasswordBtn.setEnabled(false);
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resetUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resetEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ResetOtp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ResetNewPassword = new javax.swing.JPasswordField();
        ShowPasswordReset = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        VerifyReset = new javax.swing.JButton();
        ResetPasswordBtn = new javax.swing.JButton();
        BacktoLoginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(18, 45, 110));

        LoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        LoginTitle.setText("Reset Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(LoginTitle)
                                        .addComponent(jLabel3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(LoginTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addContainerGap(35, Short.MAX_VALUE)));

        resetUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetUsernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Email Address:");

        resetEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEmailActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter OTP:");

        ResetOtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetOtpActionPerformed(evt);
            }
        });

        jLabel5.setText("New Password:");

        ResetNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetNewPasswordActionPerformed(evt);
            }
        });

        ShowPasswordReset.setText("Show Password");
        ShowPasswordReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordResetActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(18, 45, 110));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Send OTP");
        jButton1.addActionListener(evt -> {
            String user = resetUsername.getText().trim();
            String email = resetEmail.getText().trim();

            if (user.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter username and email.");
                return;
            }

            try {
                UserService us = new UserService();
                if (!us.userExists(user)) {
                    JOptionPane.showMessageDialog(this, "Username not found.");
                    return;
                }

                String storedEmail = us.getUserEmail(user);
                if (storedEmail == null || !storedEmail.equalsIgnoreCase(email)) {
                    JOptionPane.showMessageDialog(this,
                            "Email does not match our records.",
                            "Verification Failed",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Send OTP
                jButton1.setEnabled(false);
                jButton1.setText("Sending...");

                new Thread(() -> {
                    try {
                        int rnd = 100000 + new java.util.Random().nextInt(900000);
                        generatedOtp = String.valueOf(rnd);
                        verifiedEmail = email;
                        verifiedUsername = user;

                        EmailService.sendOtp(email, generatedOtp);

                        SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(this, "OTP sent to " + email);
                            ResetOtp.setEnabled(true);
                            VerifyReset.setEnabled(true);
                            resetUsername.setEnabled(false);
                            resetEmail.setEnabled(false);
                            jButton1.setText("Sent");
                        });
                    } catch (Exception e) {
                        SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(this, "Error sending email: " + e.getMessage());
                            jButton1.setEnabled(true);
                            jButton1.setText("Send OTP");
                        });
                    }
                }).start();

            } catch (Exception e) {
                e.printStackTrace();
            }
        });

        VerifyReset.setBackground(new java.awt.Color(18, 45, 110));
        VerifyReset.setForeground(new java.awt.Color(255, 255, 255));
        VerifyReset.setText("Verify");
        VerifyReset.addActionListener(evt -> {
            String input = ResetOtp.getText().trim();
            if (input.equals(generatedOtp)) {
                JOptionPane.showMessageDialog(this, "Verified! Please enter new password.");
                ResetOtp.setEnabled(false);
                VerifyReset.setEnabled(false);
                ResetNewPassword.setEnabled(true);
                ShowPasswordReset.setEnabled(true);
                ResetPasswordBtn.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid OTP.");
            }
        });

        ResetPasswordBtn.setBackground(new java.awt.Color(18, 45, 110));
        ResetPasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        ResetPasswordBtn.setText("Reset Password");
        ResetPasswordBtn.addActionListener(evt -> {
            String newPass = new String(ResetNewPassword.getPassword());
            if (newPass.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter a new password.");
                return;
            }

            try {
                UserService us = new UserService();
                if (us.updatePassword(verifiedUsername, newPass)) {
                    // Send confirmation email
                    new Thread(() -> {
                        EmailService.sendPasswordReset(verifiedEmail, newPass);
                    }).start();

                    JOptionPane.showMessageDialog(this, "Password updated successfully!\nPlease login.");
                    new LoginFrame().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update password.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating password: " + e.getMessage());
            }
        });

        BacktoLoginBtn.setBackground(new java.awt.Color(204, 0, 51));
        BacktoLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        BacktoLoginBtn.setText("Back to Login");
        BacktoLoginBtn.addActionListener(evt -> {
            new LoginFrame().setVisible(true);
            this.dispose();
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resetUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(resetEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ResetOtp, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(VerifyReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ResetNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ShowPasswordReset)
                                        .addComponent(ResetPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BacktoLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(resetUsername, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(resetEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(ResetOtp, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VerifyReset))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(ResetNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShowPasswordReset)
                                .addGap(18, 18, 18)
                                .addComponent(ResetPasswordBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BacktoLoginBtn)
                                .addGap(0, 32, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetUsernameActionPerformed
        resetEmail.requestFocus();
    }// GEN-LAST:event_resetUsernameActionPerformed

    private void resetEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetEmailActionPerformed
        jButton1.doClick(); // Send OTP
    }// GEN-LAST:event_resetEmailActionPerformed

    private void ResetOtpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetOtpActionPerformed
        VerifyReset.doClick();
    }// GEN-LAST:event_ResetOtpActionPerformed

    private void ResetNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetNewPasswordActionPerformed
        ResetPasswordBtn.doClick();
    }// GEN-LAST:event_ResetNewPasswordActionPerformed

    private void ShowPasswordResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ShowPasswordResetActionPerformed
        if (ShowPasswordReset.isSelected()) {
            ResetNewPassword.setEchoChar((char) 0);
        } else {
            ResetNewPassword.setEchoChar('*');
        }
    }// GEN-LAST:event_ShowPasswordResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPasswordFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoLoginBtn;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JPasswordField ResetNewPassword;
    private javax.swing.JTextField ResetOtp;
    private javax.swing.JButton ResetPasswordBtn;
    private javax.swing.JCheckBox ShowPasswordReset;
    private javax.swing.JButton VerifyReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField resetEmail;
    private javax.swing.JTextField resetUsername;
    // End of variables declaration//GEN-END:variables
}
