
package crs.gui;

import crs.models.User;
import crs.services.UserService;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LoginFrame.class.getName());

    private javax.swing.JButton ForgotPassBtn; // New button

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // make full screen
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UsernameTXT = new javax.swing.JTextField();
        PasswordTXT = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        ShowPassword = new javax.swing.JCheckBox();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course Recovery System - Login");

        jPanel1.setBackground(new java.awt.Color(18, 45, 110));

        LoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        LoginTitle.setText("Course Recovery System");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 220, 220));
        jLabel3.setText("Student Academic Support Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(LoginTitle)
                                        .addComponent(jLabel3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(LoginTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addContainerGap(35, Short.MAX_VALUE)));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
                javax.swing.BorderFactory.createEmptyBorder(25, 30, 25, 30)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 60, 60));
        jLabel2.setText("Password");

        UsernameTXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameTXT.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)));
        UsernameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTXTActionPerformed(evt);
            }
        });

        PasswordTXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordTXT.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)));
        PasswordTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTXTActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(18, 45, 110));
        LoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("LOGIN");
        LoginBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.setFocusPainted(false);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        ShowPassword.setBackground(new java.awt.Color(245, 245, 245));
        ShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ShowPassword.setForeground(new java.awt.Color(80, 80, 80));
        ShowPassword.setText("Show Password");
        ShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowPassword.setFocusPainted(false);
        ShowPassword.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ShowPasswordComponentShown(evt);
            }
        });
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(220, 53, 69));
        ExitBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setText("EXIT");
        ExitBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.setFocusPainted(false);
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        RegisterBtn = new javax.swing.JButton();
        RegisterBtn.setBackground(new java.awt.Color(46, 125, 50)); // Green
        RegisterBtn.setFont(new java.awt.Font("Segoe UI", 1, 16));
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Register");
        RegisterBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        RegisterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBtn.setFocusPainted(false);
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        ForgotPassBtn = new javax.swing.JButton();
        ForgotPassBtn.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPassBtn.setFont(new java.awt.Font("Segoe UI", 0, 14));
        ForgotPassBtn.setForeground(new java.awt.Color(18, 45, 110));
        ForgotPassBtn.setText("Forgot Password?");
        ForgotPassBtn.setBorderPainted(false);
        ForgotPassBtn.setContentAreaFilled(false);
        ForgotPassBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPassBtn.addActionListener(evt -> {
            new ForgotPasswordFrame().setVisible(true);
            this.dispose();
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 60, 60));
        jLabel1.setText("Username");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
                jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout
                .setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(40, 40, 40)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(UsernameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2)
                                                .addComponent(PasswordTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ShowPassword)
                                                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ForgotPassBtn)) // Add to layout
                                        .addGap(40, 40, 40)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsernameTXT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18).addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordTXT, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12).addComponent(ShowPassword).addGap(10, 10, 10).addComponent(ForgotPassBtn) // Add
                                                                                                                      // vertical
                        .addGap(10, 10, 10).addComponent(LoginBtn)
                        .addGap(12, 12, 12).addComponent(RegisterBtn).addGap(12, 12, 12).addComponent(ExitBtn)
                        .addGap(40, 40, 40)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        60, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTXTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UsernameTXTActionPerformed
        PasswordTXT.requestFocus();
    }// GEN-LAST:event_UsernameTXTActionPerformed

    private void ShowPasswordComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_ShowPasswordComponentShown
        // TODO add your handling code here:
    }// GEN-LAST:event_ShowPasswordComponentShown

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginBtnActionPerformed
        String username = UsernameTXT.getText().trim();
        String password = new String(PasswordTXT.getPassword());

        // basic validation
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter username and password.",
                    "Missing Information",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            UserService userService = new UserService();
            User user = userService.authenticate(username, password);

            // invalid credentials
            if (user == null) {
                JOptionPane.showMessageDialog(this,
                        "Invalid username or password.",
                        "Login Failed",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // inactive account
            if (!user.isActive()) {
                JOptionPane.showMessageDialog(this,
                        "Your account is deactivated. Please contact the administrator.",
                        "Access Denied",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // success - navigate directly to main menu (no popup needed)
            new MainMenuFrame(user).setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error while logging in:\n" + ex.getMessage(),
                    "System Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_LoginBtnActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ShowPasswordActionPerformed
        if (ShowPassword.isSelected()) {
            PasswordTXT.setEchoChar((char) 0);
        } else {
            PasswordTXT.setEchoChar('•'); // or '*'
        }
    }// GEN-LAST:event_ShowPasswordActionPerformed

    private void PasswordTXTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PasswordTXTActionPerformed
        LoginBtn.doClick();
    }// GEN-LAST:event_PasswordTXTActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ExitBtnActionPerformed
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to exit?",
                "Exit Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }// GEN-LAST:event_ExitBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {
        new RegisterFrame().setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JPasswordField PasswordTXT;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JTextField UsernameTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
