/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.gui;

import crs.models.User;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MainMenuFrame extends javax.swing.JFrame {

        private User currentUser;

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(MainMenuFrame.class.getName());

        /**
         * Creates new form MainMenuFrame
         */

        public MainMenuFrame() {
                initComponents();
                setLocationRelativeTo(null);
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        }

        public MainMenuFrame(User user) {
                initComponents();
                setLocationRelativeTo(null);
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                this.currentUser = user;
                applyRolePermissions();
        }

        private void applyRolePermissions() {
                if (currentUser == null)
                        return;

                String role = currentUser.getRole();
                role = (role == null) ? "" : role.trim().toUpperCase().replace(" ", "_");

                boolean isCourseAdmin = role.equals("COURSE_ADMINISTRATOR");
                boolean isAcademicOfficer = role.equals("ACADEMIC_OFFICER");

                if (isCourseAdmin) {
                        UserManagementBtn.setEnabled(true);
                        StudentManagementBtn.setEnabled(true);
                        ReportsBtn.setEnabled(true);
                        EligibilityCheckBtn.setEnabled(false);
                        CourseRecoveryPlanBtn.setEnabled(false);
                } else if (isAcademicOfficer) {
                        UserManagementBtn.setEnabled(false);
                        StudentManagementBtn.setEnabled(true);
                        ReportsBtn.setEnabled(true);
                        EligibilityCheckBtn.setEnabled(true);
                        CourseRecoveryPlanBtn.setEnabled(true);
                } else {
                        UserManagementBtn.setEnabled(false);
                        StudentManagementBtn.setEnabled(false);
                        ReportsBtn.setEnabled(false);
                        EligibilityCheckBtn.setEnabled(false);
                        CourseRecoveryPlanBtn.setEnabled(false);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                MenuTitle = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                UserManagementBtn = new javax.swing.JButton();
                StudentManagementBtn = new javax.swing.JButton();
                CourseRecoveryPlanBtn = new javax.swing.JButton();
                EligibilityCheckBtn = new javax.swing.JButton();
                ReportsBtn = new javax.swing.JButton();
                LogoutBtn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Course Recovery System - Main Menu");

                jPanel1.setBackground(new java.awt.Color(18, 45, 110));

                MenuTitle.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
                MenuTitle.setForeground(new java.awt.Color(255, 255, 255));
                MenuTitle.setText("Main Menu");

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(220, 220, 220));
                jLabel1.setText("Select a module to continue");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.CENTER)
                                                                                .addComponent(MenuTitle)
                                                                                .addComponent(jLabel1))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(MenuTitle)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(35, Short.MAX_VALUE)));

                jPanel2.setBackground(new java.awt.Color(250, 250, 250));

                UserManagementBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                UserManagementBtn.setForeground(new java.awt.Color(18, 45, 110));
                UserManagementBtn.setText("<html><center>👤 User Management</center></html>");
                UserManagementBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 10)));
                UserManagementBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                UserManagementBtn.setFocusPainted(false);
                UserManagementBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                UserManagementBtnActionPerformed(evt);
                        }
                });

                StudentManagementBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
                StudentManagementBtn.setForeground(new java.awt.Color(18, 45, 110));
                StudentManagementBtn.setText("<html><center>🎓 Student Management</center></html>");
                StudentManagementBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 10)));
                StudentManagementBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                StudentManagementBtn.setFocusPainted(false);
                StudentManagementBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                StudentManagementBtnActionPerformed(evt);
                        }
                });

                CourseRecoveryPlanBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                CourseRecoveryPlanBtn.setForeground(new java.awt.Color(18, 45, 110));
                CourseRecoveryPlanBtn.setText("<html><center>📝 Course Recovery<br>Plan</center></html>");
                CourseRecoveryPlanBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 10)));
                CourseRecoveryPlanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                CourseRecoveryPlanBtn.setFocusPainted(false);
                CourseRecoveryPlanBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CourseRecoveryPlanBtnActionPerformed(evt);
                        }
                });

                EligibilityCheckBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                EligibilityCheckBtn.setForeground(new java.awt.Color(18, 45, 110));
                EligibilityCheckBtn.setText("<html><center>✔️ Eligibility<br>Check</center></html>");
                EligibilityCheckBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 10)));
                EligibilityCheckBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                EligibilityCheckBtn.setFocusPainted(false);
                EligibilityCheckBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EligibilityCheckBtnActionPerformed(evt);
                        }
                });

                ReportsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                ReportsBtn.setForeground(new java.awt.Color(18, 45, 110));
                ReportsBtn.setText("<html><center>📊 Academic<br>Reports</center></html>");
                ReportsBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 10)));
                ReportsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                ReportsBtn.setFocusPainted(false);
                ReportsBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ReportsBtnActionPerformed(evt);
                        }
                });

                LogoutBtn.setBackground(new java.awt.Color(220, 53, 69));
                LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
                LogoutBtn.setText("<html><center>🚪 Logout</center></html>");
                LogoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
                LogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                LogoutBtn.setFocusPainted(false);
                LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                LogoutBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(UserManagementBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                380,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(StudentManagementBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                380,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(CourseRecoveryPlanBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                380,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(EligibilityCheckBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                380,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(ReportsBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                380,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(LogoutBtn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                380,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(30, 30, 30)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(jPanel2Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(UserManagementBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(StudentManagementBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(CourseRecoveryPlanBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel2Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(EligibilityCheckBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(ReportsBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(LogoutBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(30, 30, 30)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void UserManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UserManagementBtnActionPerformed
                // Use current user if available, otherwise create default admin
                User userToPass = currentUser;
                if (userToPass == null) {
                        userToPass = new User("admin", "COURSE_ADMINISTRATOR", true, "admin@example.com");
                }

                String role = (userToPass.getRole() == null) ? ""
                                : userToPass.getRole().trim().toUpperCase().replace(" ", "_");

                if (!role.equals("COURSE_ADMINISTRATOR")) {
                        JOptionPane.showMessageDialog(this,
                                        "Access denied.\nAdmins only.",
                                        "Permission Denied",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                UserManagementFrame frame = new UserManagementFrame(userToPass);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_UserManagementBtnActionPerformed

        private void EligibilityCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EligibilityCheckBtnActionPerformed
                new EligibilityFrame().setVisible(true);
        }// GEN-LAST:event_EligibilityCheckBtnActionPerformed

        private void CourseRecoveryPlanBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CourseRecoveryPlanBtnActionPerformed
                RecoveryPlanFrame frame = new RecoveryPlanFrame();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
                this.dispose();
        }// GEN-LAST:event_CourseRecoveryPlanBtnActionPerformed

        private void StudentManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_StudentManagementBtnActionPerformed
                new StudentManagementFrame().setVisible(true);
        }// GEN-LAST:event_StudentManagementBtnActionPerformed

        private void ReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ReportsBtnActionPerformed
                try {
                        // Use current user if available, otherwise create default admin
                        User userToPass = currentUser;
                        if (userToPass == null) {
                                userToPass = new User("admin", "COURSE_ADMINISTRATOR", true, "admin@example.com");
                        }

                        ReportFrame frame = new ReportFrame(userToPass);
                        frame.setLocationRelativeTo(null);
                        frame.setVisible(true);
                        this.dispose();
                } catch (Throwable ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Error opening Reports: " + ex.getMessage());
                }
        }// GEN-LAST:event_ReportsBtnActionPerformed

        private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LogoutBtnActionPerformed
                new LoginFrame().setVisible(true);
                this.dispose();
        }// GEN-LAST:event_LogoutBtnActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton CourseRecoveryPlanBtn;
        private javax.swing.JButton EligibilityCheckBtn;
        private javax.swing.JButton LogoutBtn;
        private javax.swing.JLabel MenuTitle;
        private javax.swing.JButton ReportsBtn;
        private javax.swing.JButton StudentManagementBtn;
        private javax.swing.JButton UserManagementBtn;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        // End of variables declaration//GEN-END:variables
}
