package crs.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mohamed Ahzam
 */
import javax.swing.JOptionPane;

import crs.models.RecoveryMilestone;

public class MilestoneFrame extends javax.swing.JFrame {

        // 🔹 1. DECLARE VARIABLES AT THE TOP (outside constructor)
        private String planId;
        private javax.swing.table.DefaultTableModel model;

        public MilestoneFrame(String planId) {
                this.planId = planId;
                initComponents(); // auto-generated by NetBeans

                setLocationRelativeTo(null);
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

                // Set table model
                model = new javax.swing.table.DefaultTableModel(
                                new String[] { "Week", "Task" }, 0);
                tblMilestones.setModel(model);

                loadMilestones(); // load data into table
        }

        private void loadMilestones() {
                model.setRowCount(0);

                for (RecoveryMilestone m : RecoveryMilestone.loadByPlan(planId)) {
                        model.addRow(new Object[] { m.week, m.task });
                }
        }

        private void addMilestone() {
                String week = txtWeek.getText().trim();
                String task = txtTask.getText().trim();

                if (week.isEmpty() || task.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Week and Task required.");
                        return;
                }

                RecoveryMilestone m = new RecoveryMilestone(planId, week, task);
                RecoveryMilestone.addMilestone(m);

                loadMilestones();
        }

        private void deleteMilestone() {
                int row = tblMilestones.getSelectedRow();
                if (row == -1) {
                        JOptionPane.showMessageDialog(this, "Select a row.");
                        return;
                }

                String week = model.getValueAt(row, 0).toString();
                RecoveryMilestone.deleteMilestone(planId, week);

                loadMilestones();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                txtWeek = new javax.swing.JTextField();
                txtTask = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblMilestones = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                btnAdd = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                btnClose = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                txtWeek.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtWeekActionPerformed(evt);
                        }
                });

                txtTask.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtTaskActionPerformed(evt);
                        }
                });

                tblMilestones.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null },
                                                { null, null },
                                                { null, null },
                                                { null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2"
                                }));
                jScrollPane1.setViewportView(tblMilestones);

                jLabel1.setText("Enter week");

                jLabel2.setText("Enter task");

                btnAdd.setBackground(new java.awt.Color(18, 45, 110));
                btnAdd.setForeground(new java.awt.Color(255, 255, 255));
                btnAdd.setText("Add milestone");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnDelete.setBackground(new java.awt.Color(255, 0, 0));
                btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                btnDelete.setText("Delete milestone");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnClose.setBackground(new java.awt.Color(18, 45, 110));
                btnClose.setForeground(new java.awt.Color(255, 255, 255));
                btnClose.setText("Close");
                btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCloseActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                405,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addContainerGap())
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(21, 21, 21)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(btnDelete)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(btnClose)
                                                                                                                                                .addComponent(btnAdd))
                                                                                                                                .addGap(19, 19, 19))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGap(31, 31, 31)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(txtTask,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                169,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(txtWeek,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                85,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addContainerGap(
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)))))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                135,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(59, 59, 59))
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel1)
                                                                                                .addComponent(txtWeek,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(btnAdd)))
                                                                .addGap(22, 22, 22)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(txtTask,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(43, 43, 43)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnClose)
                                                                                .addComponent(btnDelete))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtWeekActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtWeekActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtWeekActionPerformed

        private void txtTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTaskActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtTaskActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
                addMilestone();
        }// GEN-LAST:event_btnAddActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
                deleteMilestone();
        }// GEN-LAST:event_btnDeleteActionPerformed

        private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCloseActionPerformed
                dispose();
        }// GEN-LAST:event_btnCloseActionPerformed

        /**
         * @param args the command line arguments
         */

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnClose;
        private javax.swing.JButton btnDelete;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblMilestones;
        private javax.swing.JTextField txtTask;
        private javax.swing.JTextField txtWeek;
        // End of variables declaration//GEN-END:variables
}
