/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.gui;

import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import crs.models.RecoveryPlan;

/**
 *
 * @author Mohamed Ahzam
 */
public class RecoveryPlanFrame extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(RecoveryPlanFrame.class.getName());

        /**
         * Creates new form RecoveryPlanFrame
         */
        private DefaultTableModel model;

        public RecoveryPlanFrame() {
                initComponents();
                setLocationRelativeTo(null);
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

                model = new DefaultTableModel(
                                new String[] { "PlanID", "StudentID", "CourseID", "AttemptNo", "Status" },
                                0);
                tblPlans.setModel(model);

                refreshTable();
        }

        private void refreshTable() {
                model.setRowCount(0);
                for (RecoveryPlan p : RecoveryPlan.loadPlans()) {
                        model.addRow(new Object[] {
                                        p.planId, p.studentId, p.courseId, p.attemptNo, p.status
                        });
                }
        }

        private boolean isDuplicate(String studentID, String courseID) {
                for (int i = 0; i < model.getRowCount(); i++) {
                        if (model.getValueAt(i, 1).equals(studentID) &&
                                        model.getValueAt(i, 2).equals(courseID)) {
                                return true;
                        }
                }
                return false;
        }

        private void findInTable(String studentId) {
                for (int i = 0; i < model.getRowCount(); i++) {
                        String sid = model.getValueAt(i, 1).toString();
                        if (sid.equalsIgnoreCase(studentId)) {
                                tblPlans.setRowSelectionInterval(i, i);
                                tblPlans.scrollRectToVisible(
                                                tblPlans.getCellRect(i, 0, true));
                                return;
                        }
                }
                JOptionPane.showMessageDialog(this,
                                "No records found for: " + studentId);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel8 = new javax.swing.JPanel();
                MenuTitle4 = new javax.swing.JLabel();
                jPanelCard = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                txtStudentID = new javax.swing.JTextField();
                btnSearch = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                txtCourseID = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                txtAttemptNo = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                txtStatus = new javax.swing.JTextField();
                btnAdd = new javax.swing.JButton();
                btnReload = new javax.swing.JButton();
                jScrollPane3 = new javax.swing.JScrollPane();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblPlans = new javax.swing.JTable();
                btnDelete = new javax.swing.JButton();
                btnReturn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel8.setBackground(new java.awt.Color(18, 45, 110));

                MenuTitle4.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
                MenuTitle4.setForeground(new java.awt.Color(255, 255, 255));
                MenuTitle4.setText("Recovery Plan");

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(MenuTitle4)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel8Layout.setVerticalGroup(
                                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(MenuTitle4)
                                                                .addContainerGap(35, Short.MAX_VALUE)));

                jPanelCard.setBackground(new java.awt.Color(255, 255, 255));
                jPanelCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));

                jLabel1.setText("Student ID");

                btnSearch.setBackground(new java.awt.Color(18, 45, 110));
                btnSearch.setForeground(new java.awt.Color(255, 255, 255));
                btnSearch.setText("Search");
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSearchActionPerformed(evt);
                        }
                });

                jLabel2.setText("Course ID");

                jButton1.setBackground(new java.awt.Color(18, 45, 110));
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Open Milestones");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel3.setText("Attempt No.");

                jLabel4.setText("Status");

                btnAdd.setBackground(new java.awt.Color(18, 45, 110));
                btnAdd.setForeground(new java.awt.Color(255, 255, 255));
                btnAdd.setText("Add Plan");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnReload.setBackground(new java.awt.Color(46, 125, 50));
                btnReload.setForeground(new java.awt.Color(255, 255, 255));
                btnReload.setText("Refresh Table");
                btnReload.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReloadActionPerformed(evt);
                        }
                });

                tblPlans.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane1.setViewportView(tblPlans);

                jScrollPane3.setViewportView(jScrollPane1);

                btnDelete.setBackground(new java.awt.Color(255, 0, 0));
                btnDelete.setForeground(new java.awt.Color(255, 255, 255));
                btnDelete.setText("Delete Selected Plan");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnReturn.setBackground(new java.awt.Color(204, 0, 0));
                btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnReturn.setForeground(new java.awt.Color(255, 255, 255));
                btnReturn.setText("← RETURN");
                btnReturn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReturnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanelCardLayout = new javax.swing.GroupLayout(jPanelCard);
                jPanelCard.setLayout(jPanelCardLayout);
                jPanelCardLayout.setHorizontalGroup(
                                jPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCardLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanelCardLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanelCardLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                80,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel3,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(txtStudentID,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                150,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(txtCourseID)
                                                                                                                .addComponent(txtAttemptNo)
                                                                                                                .addComponent(txtStatus))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jButton1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(btnSearch,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(jPanelCardLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                .addComponent(btnReload,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnAdd,
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                120,
                                                                                                                Short.MAX_VALUE))
                                                                                .addComponent(btnReturn))
                                                                .addGap(30, 30, 30)
                                                                .addGroup(
                                                                                jPanelCardLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jScrollPane3,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                500,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanelCardLayout.createSequentialGroup()
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                                .addComponent(btnDelete)))
                                                                .addGap(20, 20, 20)));
                jPanelCardLayout.setVerticalGroup(
                                jPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCardLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanelCardLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanelCardLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addComponent(txtStudentID,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(btnSearch,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(txtCourseID,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jButton1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(txtAttemptNo,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanelCardLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(txtStatus,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(30, 30, 30)
                                                                                                .addComponent(btnAdd,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnReload,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                50,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnReturn,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanelCardLayout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jScrollPane3,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                340,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(btnDelete,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                35,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(20, 20, 20)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jPanelCard,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(50, 50, 50)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel8,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jPanelCard,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(30, 30, 30)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed
                String target = txtStudentID.getText().trim();
                if (target.isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                                        "Enter Student ID to search.");
                        return;
                }
                findInTable(target);
        }// GEN-LAST:event_btnSearchActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
                String studentID = txtStudentID.getText().trim();
                String courseID = txtCourseID.getText().trim();
                String attempt = txtAttemptNo.getText().trim();
                String status = txtStatus.getText().trim();

                if (studentID.isEmpty() || courseID.isEmpty()
                                || attempt.isEmpty() || status.isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                                        "All fields required.");
                        return;
                }

                if (isDuplicate(studentID, courseID)) {
                        JOptionPane.showMessageDialog(this,
                                        "Duplicate entry exists.");
                        return;
                }

                String planID = RecoveryPlan.generatePlanID();

                RecoveryPlan newPlan = new RecoveryPlan(
                                planID, studentID, courseID,
                                Integer.parseInt(attempt), status,
                                "", ""); // Empty recommendation and grade

                RecoveryPlan.addPlan(newPlan);
                refreshTable();

                crs.services.EmailService.sendRecoveryPlanAlert(studentID + "@crs.edu", newPlan.toString());

                JOptionPane.showMessageDialog(this,
                                "Plan added successfully!");
        }// GEN-LAST:event_btnAddActionPerformed

        private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReloadActionPerformed
                refreshTable();
                // TODO add your handling code here
        }// GEN-LAST:event_btnReloadActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
                int row = tblPlans.getSelectedRow();

                if (row == -1) {
                        JOptionPane.showMessageDialog(this,
                                        "Select a row to delete.");
                        return;
                }

                String planId = model.getValueAt(row, 0).toString();
                RecoveryPlan.deletePlan(planId);

                refreshTable();
                JOptionPane.showMessageDialog(this,
                                "Entry deleted.");
        }// GEN-LAST:event_btnDeleteActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                int row = tblPlans.getSelectedRow();

                if (row == -1) {
                        JOptionPane.showMessageDialog(this,
                                        "Please select a recovery plan first.");
                        return;
                }

                String planId = model.getValueAt(row, 0).toString();

                MilestoneFrame milestoneGUI = new MilestoneFrame(planId);
                milestoneGUI.setVisible(true);
        }// GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new RecoveryPlanFrame().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel MenuTitle4;
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnReload;
        private javax.swing.JButton btnReturn;
        private javax.swing.JButton btnSearch;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblPlans;
        private javax.swing.JTextField txtAttemptNo;
        private javax.swing.JTextField txtCourseID;
        private javax.swing.JTextField txtStatus;
        private javax.swing.JTextField txtStudentID;
        private javax.swing.JPanel jPanelCard;
        // End of variables declaration//GEN-END:variables

        private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {
                new MainMenuFrame().setVisible(true);
                this.dispose();
        }
}
