package crs.gui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class StudentManagementFrame extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(StudentManagementFrame.class.getName());

        private static final String STUDENT_FILE = "student_information.csv";
        private DefaultTableModel model;

        /**
         * Creates new form StudentManagementFrame
         */
        public StudentManagementFrame() {
                initComponents();
                setLocationRelativeTo(null);
                setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

                model = (DefaultTableModel) tblStudents.getModel();
                loadStudents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                MenuTitle = new javax.swing.JLabel();
                btnReturn = new javax.swing.JButton();
                jPanelCenter = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblStudents = new javax.swing.JTable();
                jPanelCard = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Course Recovery System - Student Management");

                jPanel1.setBackground(new java.awt.Color(18, 45, 110));

                MenuTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                MenuTitle.setForeground(new java.awt.Color(255, 255, 255));
                MenuTitle.setText("Student Management");

                btnReturn.setBackground(new java.awt.Color(204, 0, 0));
                btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btnReturn.setForeground(new java.awt.Color(255, 255, 255));
                btnReturn.setText("← RETURN");
                btnReturn.setBorderPainted(false);
                btnReturn.setFocusPainted(false);
                btnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnReturn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReturnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(MenuTitle)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(btnReturn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                150,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(MenuTitle)
                                                                                .addComponent(btnReturn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                45,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)));

                jPanelCenter.setBackground(new java.awt.Color(250, 250, 250));

                tblStudents.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "Student ID", "Full Name", "Major", "Year", "Email", "CGPA", "Failed",
                                                "Eligible"
                                }) {
                        boolean[] canEdit = new boolean[] {
                                        false, false, false, false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(tblStudents);

                // Set column widths for better display
                if (tblStudents.getColumnModel().getColumnCount() > 0) {
                        tblStudents.getColumnModel().getColumn(0).setPreferredWidth(100); // Student ID
                        tblStudents.getColumnModel().getColumn(1).setPreferredWidth(150); // Full Name
                        tblStudents.getColumnModel().getColumn(2).setPreferredWidth(120); // Major
                        tblStudents.getColumnModel().getColumn(3).setPreferredWidth(60); // Year
                        tblStudents.getColumnModel().getColumn(4).setPreferredWidth(220); // Email (wider)
                        tblStudents.getColumnModel().getColumn(5).setPreferredWidth(70); // CGPA
                        tblStudents.getColumnModel().getColumn(6).setPreferredWidth(70); // Failed
                        tblStudents.getColumnModel().getColumn(7).setPreferredWidth(80); // Eligible
                }

                jPanelCard.setBackground(new java.awt.Color(255, 255, 255));
                jPanelCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)));

                javax.swing.GroupLayout jPanelCardLayout = new javax.swing.GroupLayout(jPanelCard);
                jPanelCard.setLayout(jPanelCardLayout);
                jPanelCardLayout.setHorizontalGroup(
                                jPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809,
                                                                Short.MAX_VALUE));
                jPanelCardLayout.setVerticalGroup(
                                jPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602,
                                                                Short.MAX_VALUE));

                javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
                jPanelCenter.setLayout(jPanelCenterLayout);
                jPanelCenterLayout.setHorizontalGroup(
                                jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCenterLayout.createSequentialGroup()
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jPanelCard,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(50, 50, 50)));
                jPanelCenterLayout.setVerticalGroup(
                                jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelCenterLayout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jPanelCard,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(30, 30, 30)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 7, Short.MAX_VALUE)
                                                                .addComponent(jPanelCenter,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
                new MainMenuFrame().setVisible(true);
                this.dispose();
        }// GEN-LAST:event_btnReturnActionPerformed

        private void loadStudents() {
                model.setRowCount(0);

                try {
                        // Use EligibilityService to get all student data with CGPA and eligibility
                        crs.services.EligibilityService eligibilityService = new crs.services.EligibilityService();
                        java.util.List<crs.services.EligibilityService.EligibilityResult> students = eligibilityService
                                        .listAll();

                        for (crs.services.EligibilityService.EligibilityResult student : students) {
                                String cgpaStr = String.format("%.2f", student.cgpa);
                                String failedStr = String.valueOf(student.failed);
                                String eligibleStr = student.eligible ? "Yes" : "No";

                                model.addRow(new Object[] {
                                                student.studentId,
                                                student.fullName,
                                                student.major,
                                                student.year,
                                                student.email,
                                                cgpaStr,
                                                failedStr,
                                                eligibleStr
                                });
                        }
                } catch (Exception ex) {
                        logger.log(java.util.logging.Level.SEVERE, "Failed to load students", ex);
                        JOptionPane.showMessageDialog(this, "Error loading students: " + ex.getMessage(), "Load Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new StudentManagementFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel MenuTitle;
        private javax.swing.JButton btnReturn;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanelCenter;
        private javax.swing.JPanel jPanelCard;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable tblStudents;
        // End of variables declaration//GEN-END:variables
}
